      SUBROUTINE closeim(lout)
      
c (c) Michiel Hogerheijde / Floris van der Tak 2000
c     michiel@strw.leidenuniv.nl, vdtak@sron.rug.nl
c     http://www.strw.leidenuniv.nl/~michiel
c     http://www.sron.rug.nl/~vdtak
c
c     This file is part of the 'ratran' molecular excitation and
c     radiative transfer code. The one-dimensional version of this code
c     is publicly available; the two-dimensional version is available on
c     collaborative basis. Although the code has been thoroughly tested,
c     the authors do not claim it is free of errors or that it gives
c     correct results in all situations. Any publication making use of
c     this code should include a reference to Hogerheijde & van der Tak,
c     2000, A&A 362, 697.

c     Writes out history info for image then closes up shop!
c     
c     inputs: 
c          lout    -- miriad handle for file

      
      IMPLICIT NONE
      INCLUDE 'skycommon.inc'
      INTEGER lout
      
      call hisopen(lout,'write')
      call hiswrite(lout,'Image generated by SKY')
      call hisclose(lout)

      call xyclose(lout)
      
      RETURN
      END
